---
name: Vaultwarden
version: "1.0.3"
slug: vaultwarden
description: Open source password management solution based on Vaultwarden
url: https://github.com/mariorasch/ha-add-ons/vaultwarden
webui: "[PROTO:ssl]://[HOST]:[PORT:7277]"
init: false
arch:
  - aarch64
ports:
  7277/tcp: 7277
ports_description:
  7277/tcp: Vaultwarden web interface & REST API
map:
  - ssl
options:
  ssl: false
  certfile: ""
  keyfile: ""
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  ssl: bool
  certfile: str?
  keyfile: str?
  request_size_limit: int?
image: "ghcr.io/mariorasch/ha-add-ons/ha-add-on-vaultwarden"
